# 📝 Prompts 包：集中管理所有 Prompt 模板
from services.prompts.chat_prompt import CHAT_SYSTEM_PROMPT, CHAT_USER_PROMPT
from services.prompts.memory_prompt import (
    CATEGORY_MEMORY_EXTRACTION_PROMPT,
    CORE_SELF_EXTRACTION_REQUIREMENTS,
    EPISODIC_MEMORY_EXTRACTION_REQUIREMENTS,
    GENERIC_CATEGORY_EXTRACTION_REQUIREMENTS,
    KNOWLEDGE_BASE_EXTRACTION_REQUIREMENTS,
    MEMORY_EXTRACTION_PROMPT,
    SOCIAL_GRAPH_EXTRACTION_REQUIREMENTS,
)
from services.prompts.onboarding_prompt import DYNAMIC_CATEGORY_PROMPT
from services.prompts.lifecycle_prompt import MEMORY_MERGE_PROMPT

__all__ = [
    "CHAT_SYSTEM_PROMPT",
    "CHAT_USER_PROMPT",
    "CATEGORY_MEMORY_EXTRACTION_PROMPT",
    "CORE_SELF_EXTRACTION_REQUIREMENTS",
    "EPISODIC_MEMORY_EXTRACTION_REQUIREMENTS",
    "GENERIC_CATEGORY_EXTRACTION_REQUIREMENTS",
    "KNOWLEDGE_BASE_EXTRACTION_REQUIREMENTS",
    "MEMORY_EXTRACTION_PROMPT",
    "SOCIAL_GRAPH_EXTRACTION_REQUIREMENTS",
    "DYNAMIC_CATEGORY_PROMPT",
    "MEMORY_MERGE_PROMPT",
]
